spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1/testdatabase  # Change IP if needed
    username: postgres
    password: Prasad@123
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update